<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" tests="29" skipped="0" failures="0" errors="0" timestamp="2020-01-15T02:08:17" hostname="localhost" time="3.855">
  <properties/>
  <testcase name="testPollHeartbeatAwakesHeartbeatThread" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="2.223"/>
  <testcase name="testJoinGroupRequestWithFencedInstanceIdException" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.05"/>
  <testcase name="testWakeupAfterSyncGroupReceivedExternalCompletion" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.114"/>
  <testcase name="testCoordinatorDiscoveryBackoff" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.002"/>
  <testcase name="testJoinGroupRequestTimeout" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.002"/>
  <testcase name="testLookupCoordinator" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.001"/>
  <testcase name="testSyncGroupRequestWithFencedInstanceIdException" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.004"/>
  <testcase name="testWakeupAfterJoinGroupSentExternalCompletion" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.212"/>
  <testcase name="testJoinGroupRequestWithMemberIdRequired" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.003"/>
  <testcase name="testHeartbeatRequestWithFencedInstanceIdException" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.025"/>
  <testcase name="testWakeupAfterJoinGroupSent" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.21"/>
  <testcase name="testHandleLeaveGroupResponseWithException" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.004"/>
  <testcase name="testWakeupAfterJoinGroupReceivedExternalCompletion" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.214"/>
  <testcase name="testWakeupInOnJoinComplete" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.105"/>
  <testcase name="testWakeupAfterSyncGroupSent" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.106"/>
  <testcase name="testGroupMaxSizeExceptionIsFatal" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.002"/>
  <testcase name="testWakeupAfterSyncGroupSentExternalCompletion" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.209"/>
  <testcase name="testWakeupAfterSyncGroupReceived" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.104"/>
  <testcase name="testMetrics" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.003"/>
  <testcase name="testJoinGroupRequestWithGroupInstanceIdNotFound" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.001"/>
  <testcase name="testHandleNormalLeaveGroupResponse" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.003"/>
  <testcase name="testLeaveGroupSentWithGroupInstanceIdUnSet" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.005"/>
  <testcase name="testHandleMultipleMembersLeaveGroupResponse" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.003"/>
  <testcase name="testUncaughtExceptionInHeartbeatThread" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.029"/>
  <testcase name="testHandleLeaveGroupResponseWithEmptyMemberResponse" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.002"/>
  <testcase name="testTimeoutAndRetryJoinGroupIfNeeded" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.004"/>
  <testcase name="testAuthenticationErrorInEnsureCoordinatorReady" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.001"/>
  <testcase name="testJoinGroupRequestMaxTimeout" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.002"/>
  <testcase name="testWakeupAfterJoinGroupReceived" classname="org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest" time="0.208"/>
  <system-out><![CDATA[[2020-01-15 10:08:19,791] ERROR Received fatal exception: group.instance.id gets fenced (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:612)
[2020-01-15 10:08:19,961] ERROR Received fatal exception: group.instance.id gets fenced (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:719)
[2020-01-15 10:08:20,189] ERROR Received fatal exception: group.instance.id gets fenced (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:1014)
[2020-01-15 10:08:20,190] ERROR Caught fenced group.instance.id Optional.empty error in heartbeat thread (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:1278)
[2020-01-15 10:08:20,417] ERROR LeaveGroup request failed with error: The coordinator is not aware of this member. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:972)
[2020-01-15 10:08:20,844] ERROR Attempt to join group failed due to fatal error: The consumer group has reached its max size. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:620)
[2020-01-15 10:08:21,192] ERROR Heartbeat thread failed due to unexpected error (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:1303)
java.lang.RuntimeException
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinatorTest.testUncaughtExceptionInHeartbeatThread(AbstractCoordinatorTest.java:519)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
